# SPDX-FileCopyrightText: Copyright (c) 2022-2026 Objectionary.com
# SPDX-License-Identifier: MIT

version = 1
[[annotations]]
path = [
    ".DS_Store",
    ".gitattributes",
    ".gitignore",
    "**.json",
    "**.md",
    "**.txt",
    "**/.DS_Store",
    "**/.gitignore",
    "**/*.csv",
    "**/*.jpg",
    "**/*.json",
    "**/*.md",
    "**/*.pdf",
    "**/*.png",
    "**/*.svg",
    "**/*.txt",
    "**/*.vm",
    "**/CNAME",
    "README.md",
    "renovate.json",
    "src/test/resources/com/yegor256/jucs/bar/y.text",
    "src/test/resources/com/yegor256/jucs/x.text",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (c) 2022-2026 Objectionary.com"
SPDX-License-Identifier = "MIT"
